---

- hosts: docker
  become: yes
  remote_user: root
  vars:
    docker-engine: docker.io
    docker-deamon: docker
    docker-image: dockernaveen02/vprofile-app:latest
  tasks:

    - name: install docker engine 
      apt:
        name: "{{docker-engine}}"
        state: present

    - name: start docker deamon process
      service:
        name: "{{docker-deamon}}"
        state: started
        enabled: yes

    - name: pull docker image from hub
      docker_image:
        name: "{{docker-image}}"
         source: pull

    - name: Run docker container
      docker_container:
        name: vprofile-app
        image: "{{docker-image}}"
        state: started
        restart: yes
        ports:
         - "8080:8080"
